"""
State definitions for the LangGraph workflow
"""
from typing import Dict, Any, TypedDict, List, Optional, Tuple, Annotated
from jsonpatch import PatchOperation
from operator import add
from langchain_core.messages import BaseMessage

from .utils.schema_tools import JSONPatchOperation

class JSONEditState(TypedDict):
    """State for JSON editing workflow"""
    messages: Annotated[List[BaseMessage], add]
    conversation_id: str
    json_data: Dict[str, Any]
    user_input: str
    response: str
    current_inci: str
    edit_history: Optional[List[Tuple[str, str]]]  # (instruction, timestamp)
    error: Optional[str]
    last_patches: Optional[List[PatchOperation]]
    fast_patches: Optional[List[PatchOperation]]
    fast_done: bool # node status tracker
    fallback_used: bool # node status tracker (if fallback node is called)
    structured_sections: Optional[Dict[str, List[Dict]]] # parsed toxicology sections
    patch_op: Optional[JSONPatchOperation] # patch opereation generated by llm
    patch_success: bool # patch status (this flag will be set to True if a valid patch is generated)

class SimpleJSONEditState(TypedDict):
    """Simplified state for linear JSON editing workflow"""
    # Input
    user_input: str
    conversation_id: Optional[str]
    inci_name: Optional[str]
    
    # Data
    json_data: dict
    
    # Processing
    parsed_instruction: Optional[dict]  # Extracted fields/values
    
    # Output
    response: str
    error: Optional[str]
    
    # Chat history
    messages: List[BaseMessage]

class ToxicologyData(TypedDict):
    """Structure for toxicology data entries"""
    data: List[str]
    reference: Dict[str, Optional[str]]
    replaced: Dict[str, str]
    source: str
    statement: Optional[str]
